-- VHDL Entity tcl_test1.rom.symbol
--
-- Created:
--          by - juw48.UNKNOWN (sb14)
--          at - 22:19:26 02/25/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY rom IS
   PORT( 
      addr : IN     std_logic_vector (3 DOWNTO 0);
      clk  : IN     std_logic;
      high : OUT    std_logic_vector (7 DOWNTO 0);
      low  : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END rom ;

--
-- VHDL Architecture tcl_test1.rom.struct
--
-- Created:
--          by - juw48.UNKNOWN (sb14)
--          at - 22:19:26 02/25/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF rom IS

   -- Architecture declarations

   -- Internal signal declarations


   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'rom'
   TYPE MW_U_1ROM_TYPE IS ARRAY(15 DOWNTO 0) OF std_logic_vector(7 DOWNTO 0);
   SIGNAL mw_U_1rom_table : MW_U_1ROM_TYPE;
   SIGNAL mw_U_1addr_int : INTEGER := 0 ;

   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'rom'
   TYPE MW_U_2ROM_TYPE IS ARRAY(15 DOWNTO 0) OF std_logic_vector(7 DOWNTO 0);
   SIGNAL mw_U_2rom_table : MW_U_2ROM_TYPE;
   SIGNAL mw_U_2addr_int : INTEGER := 0 ;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'rom'
   mw_U_1addr_int <= (CONV_INTEGER(unsigned(addr)));
   u_1rom_table_proc : PROCESS ( mw_U_1addr_int )
   BEGIN
      CASE mw_U_1addr_int IS 
         WHEN 0 => mw_U_1rom_table(0) <= "00000000";
         WHEN 1 => mw_U_1rom_table(1) <= "00000001";
         WHEN 2 => mw_U_1rom_table(2) <= "00000010";
         WHEN 3 => mw_U_1rom_table(3) <= "00000011";
         WHEN 4 => mw_U_1rom_table(4) <= "00000100";
         WHEN 5 => mw_U_1rom_table(5) <= "00000101";
         WHEN 6 => mw_U_1rom_table(6) <= "00000110";
         WHEN 7 => mw_U_1rom_table(7) <= "00000111";
         WHEN 8 => mw_U_1rom_table(8) <= "00001000";
         WHEN 9 => mw_U_1rom_table(9) <= "00001001";
         WHEN 10 => mw_U_1rom_table(10) <= "00001010";
         WHEN 11 => mw_U_1rom_table(11) <= "00001011";
         WHEN 12 => mw_U_1rom_table(12) <= "00001100";
         WHEN 13 => mw_U_1rom_table(13) <= "00001101";
         WHEN 14 => mw_U_1rom_table(14) <= "00001110";
         WHEN 15 => mw_U_1rom_table(15) <= "00001111";
         WHEN OTHERS => mw_U_1rom_table(mw_U_1addr_int) <= (OTHERS => 'X') ;
      END CASE;
   END PROCESS ;
   
   u_1rom_read_proc : PROCESS ( clk )
   BEGIN
      IF  (clk'EVENT AND clk='1')  THEN
         high <= mw_U_1rom_table(mw_U_1addr_int);
      END IF;
   END PROCESS ;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'rom'
   mw_U_2addr_int <= (CONV_INTEGER(unsigned(addr)));
   u_2rom_table_proc : PROCESS ( mw_U_2addr_int )
   BEGIN
      CASE mw_U_2addr_int IS 
         WHEN 0 => mw_U_2rom_table(0) <= "00010000";
         WHEN 1 => mw_U_2rom_table(1) <= "00100000";
         WHEN 2 => mw_U_2rom_table(2) <= "00110000";
         WHEN 3 => mw_U_2rom_table(3) <= "01000000";
         WHEN 4 => mw_U_2rom_table(4) <= "01010000";
         WHEN 5 => mw_U_2rom_table(5) <= "01100000";
         WHEN 6 => mw_U_2rom_table(6) <= "01110000";
         WHEN 7 => mw_U_2rom_table(7) <= "10000000";
         WHEN 8 => mw_U_2rom_table(8) <= "10010000";
         WHEN 9 => mw_U_2rom_table(9) <= "10100000";
         WHEN 10 => mw_U_2rom_table(10) <= "10110000";
         WHEN 11 => mw_U_2rom_table(11) <= "11000000";
         WHEN 12 => mw_U_2rom_table(12) <= "11010000";
         WHEN 13 => mw_U_2rom_table(13) <= "11100000";
         WHEN 14 => mw_U_2rom_table(14) <= "11110000";
         WHEN 15 => mw_U_2rom_table(15) <= "00000000";
         WHEN OTHERS => mw_U_2rom_table(mw_U_2addr_int) <= (OTHERS => 'X') ;
      END CASE;
   END PROCESS ;
   
   u_2rom_read_proc : PROCESS ( clk )
   BEGIN
      IF  (clk'EVENT AND clk='1')  THEN
         low <= mw_U_2rom_table(mw_U_2addr_int);
      END IF;
   END PROCESS ;

   -- Instance port mappings.

END struct;
